#!/bin/bash
set -e

if command -v systemctl > /dev/null 2>&1; then
    systemctl stop wireguard-webmanager.service || true
    systemctl stop wireguard-webmanager-worker.service || true
    systemctl disable wireguard-webmanager.service || true
    systemctl disable wireguard-webmanager-worker.service || true
fi
